version : 2 

sources: 
  - name: default
    schema: police_incidents_warehouse
    tables:
      - name: raw_ingest

  
models:
  - name : stg_incidence_sup_comb
    columns:
      - name: hash_key
        type: STRING
        description: "A hash key on row to uniquely identifying the incident."
        tests:
          - not_null
  - name: stg_sup_dist
  - name: stg_incidence_data